spring.application.name=Gamer Profile

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.sql.init.mode=always

steam.api.base-url=https://api.steampowered.com
steam.api.key=${STEAM_API_KEY}
steam.api.steam-id=${STEAM_ID64}
steam.auth.return-url=${STEAM_AUTH_RETURN_URL:http://localhost:8080/auth/steam/callback}
steam.auth.realm=${STEAM_AUTH_REALM:http://localhost:8080/}
